# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  [push]

permissions:
  contents: read

jobs:
  run_test_suite:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with pytest
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        pytest --cov-report html test --cov=.\
    - name: Static analysis
      run: |
        pylint --disable line-too-long --disable wrong-import-order --disable no-name-in-module ./src
